name: LIFFT
description: LEADER IN FITNESS AND FOOD TRACKING

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Third party packages
  http: ^0.12.0+4
  intl: ^0.16.1
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.13.6
  provider: ^4.0.1
  cached_network_image: ^2.0.0
  table_calendar: ^2.2.2
  #state_management
  stacked: ^1.6.0
  stacked_services: ^0.4.0

  #routing
  auto_route: ^0.5.0


  #inversion of control
  injectable: ^0.4.0+1
  get_it: ^4.0.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner:
  auto_route_generator:
  injectable_generator:

  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/muscle_icons/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
